# Generated by Django 4.0.1 on 2022-01-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'งาน', 'verbose_name_plural': 'ข้อมูลงาน'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='storetask',
        ),
    ]
